---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones

  hetzner:
    class: octodns_hetzner.HetznerProvider
    token: env/HETZNER_TOKEN

zones:
  tharavad.xyz.:
    sources:
      - config
    targets:
      - hetzner
